#!/bin/bash

cd $(dirname "$0")/..

trap "rm -f ./_test.onedrive_token" EXIT
go run _tools/authtool.go oauth2 https://login.microsoftonline.com/common/oauth2/v2.0/authorize https://login.microsoftonline.com/common/oauth2/v2.0/token keyring:objfs/onedrive_client_secret ./_test.onedrive_token && \
go test "$@"
